/*
 * generated by Xtext
 */
package rethink.uml.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractClassDiagramValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(rethink.uml.classDiagram.ClassDiagramPackage.eINSTANCE);
		return result;
	}
}
