sudo: required

language: node_js

node_js:
  - "6"

services:
  - docker

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - docker pull rethink/catalogue-broker
  - docker run -it -d --name="catalogue-broker" --net=host --expose=433 rethink/catalogue-broker
  - git clone https://github.com/reTHINK-project/testbeds.git
  - cd /testbeds/nodes/PT-node/tests
  - docker run -it -d --net=host --name="catalogue-database" catalogue-database -host localhost

install:
  - npm install

script:
  - karma start
