sudo: required

language: node_js

node_js:
  - "6"

services:
  - docker

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - docker pull rethink/catalogue-broker
  - docker run -it -d --name="catalogue-broker" --net=host --expose=433 rethink/catalogue-broker
  - docker pull rethink/catalogue-test-client:dev
  - docker run -it -d --net=host --name="catalogue-database" rethink/catalogue-test-client:dev -host localhost

install:
  - npm install

script:
  - karma start
