/*
 * generated by Xtext
 */
package rethink.uml;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ClassDiagramRuntimeModule extends rethink.uml.AbstractClassDiagramRuntimeModule {

}
