/*
 * generated by Xtext
 */
package rethink.uml;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ClassDiagramStandaloneSetup extends ClassDiagramStandaloneSetupGenerated{

	public static void doSetup() {
		new ClassDiagramStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

