/*
 * generated by Xtext
 */
package rethink.uml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ClassDiagramUiModule extends rethink.uml.ui.AbstractClassDiagramUiModule {
	public ClassDiagramUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
