/**
 * generated by Xtext
 */
package rethink.uml.ui.contentassist;

import rethink.uml.ui.contentassist.AbstractClassDiagramProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ClassDiagramProposalProvider extends AbstractClassDiagramProposalProvider {
}
