/*
 * generated by Xtext
 */
package rethink.uml.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import rethink.uml.services.ClassDiagramGrammarAccess;

public class ClassDiagramParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ClassDiagramGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected rethink.uml.parser.antlr.internal.InternalClassDiagramParser createParser(XtextTokenStream stream) {
		return new rethink.uml.parser.antlr.internal.InternalClassDiagramParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "DomainModel";
	}
	
	public ClassDiagramGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ClassDiagramGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
