/*
 * generated by Xtext
 */
package rethink.uml.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ClassDiagramAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("rethink/uml/parser/antlr/internal/InternalClassDiagram.tokens");
	}
}
