@startuml
GenericHypertyStaticData <|-- CommunicationHypertyStaticData
GenericHypertyStaticData <|-- IdentityHypertyStaticData
GenericHypertyStaticData <|-- ContextHypertyStaticData
class GenericHypertyStaticData {
Identification : String
Administrative domain : TBD
Type : Communication | Identity | Context
Description : String
Configuration data : TBD
Policies : TBD
}

class CommunicationHypertyStaticData {
Communication Object Schema : TBD
}

class IdentityHypertyStaticData {
Identity Object Schema : TBD
}

class ContextHypertyStaticData {
Context Object Schema : TBD
}
 
@enduml
