window.esdocSearchIndex = [
  [
    "service-framework/src/bus/bus.js~bus",
    "class/src/bus/Bus.js~Bus.html",
    "<span>Bus</span> <span class=\"search-result-import-path\">service-framework/src/bus/Bus.js</span>",
    "class"
  ],
  [
    "service-framework/src/syncher/proxyobject.js~changetype",
    "variable/index.html#static-variable-ChangeType",
    "<span>ChangeType</span> <span class=\"search-result-import-path\">service-framework/src/syncher/ProxyObject.js</span>",
    "variable"
  ],
  [
    "service-framework/src/syncher/syncobject.js~changetype",
    "variable/index.html#static-variable-ChangeType",
    "<span>ChangeType</span> <span class=\"search-result-import-path\">service-framework/src/syncher/SyncObject.js</span>",
    "variable"
  ],
  [
    "service-framework/src/identity/crypto.js~crypto",
    "class/src/identity/Crypto.js~Crypto.html",
    "<span>Crypto</span> <span class=\"search-result-import-path\">service-framework/src/identity/Crypto.js</span>",
    "class"
  ],
  [
    "service-framework/src/syncher/dataobject.js~dataobject",
    "class/src/syncher/DataObject.js~DataObject.html",
    "<span>DataObject</span> <span class=\"search-result-import-path\">service-framework/src/syncher/DataObject.js</span>",
    "class"
  ],
  [
    "service-framework/src/syncher/dataobjectchild.js~dataobjectchild",
    "class/src/syncher/DataObjectChild.js~DataObjectChild.html",
    "<span>DataObjectChild</span> <span class=\"search-result-import-path\">service-framework/src/syncher/DataObjectChild.js</span>",
    "class"
  ],
  [
    "service-framework/src/syncher/dataobjectobserver.js~dataobjectobserver",
    "class/src/syncher/DataObjectObserver.js~DataObjectObserver.html",
    "<span>DataObjectObserver</span> <span class=\"search-result-import-path\">service-framework/src/syncher/DataObjectObserver.js</span>",
    "class"
  ],
  [
    "service-framework/src/syncher/dataobjectreporter.js~dataobjectreporter",
    "class/src/syncher/DataObjectReporter.js~DataObjectReporter.html",
    "<span>DataObjectReporter</span> <span class=\"search-result-import-path\">service-framework/src/syncher/DataObjectReporter.js</span>",
    "class"
  ],
  [
    "service-framework/src/discovery/discovery.js~discovery",
    "class/src/discovery/Discovery.js~Discovery.html",
    "<span>Discovery</span> <span class=\"search-result-import-path\">service-framework/src/discovery/Discovery.js</span>",
    "class"
  ],
  [
    "service-framework/src/utils/eventemitter.js~eventemitter",
    "class/src/utils/EventEmitter.js~EventEmitter.html",
    "<span>EventEmitter</span> <span class=\"search-result-import-path\">service-framework/src/utils/EventEmitter.js</span>",
    "class"
  ],
  [
    "service-framework/src/identity/guifake.js~guifake",
    "class/src/identity/GuiFake.js~GuiFake.html",
    "<span>GuiFake</span> <span class=\"search-result-import-path\">service-framework/src/identity/GuiFake.js</span>",
    "class"
  ],
  [
    "service-framework/src/identity/identity.js~identity",
    "class/src/identity/Identity.js~Identity.html",
    "<span>Identity</span> <span class=\"search-result-import-path\">service-framework/src/identity/Identity.js</span>",
    "class"
  ],
  [
    "service-framework/src/identity/identitymodule.js~identitymodule",
    "class/src/identity/IdentityModule.js~IdentityModule.html",
    "<span>IdentityModule</span> <span class=\"search-result-import-path\">service-framework/src/identity/IdentityModule.js</span>",
    "class"
  ],
  [
    "service-framework/src/bus/messagebus.js~messagebus",
    "class/src/bus/MessageBus.js~MessageBus.html",
    "<span>MessageBus</span> <span class=\"search-result-import-path\">service-framework/src/bus/MessageBus.js</span>",
    "class"
  ],
  [
    "service-framework/src/bus/minibus.js~minibus",
    "class/src/bus/MiniBus.js~MiniBus.html",
    "<span>MiniBus</span> <span class=\"search-result-import-path\">service-framework/src/bus/MiniBus.js</span>",
    "class"
  ],
  [
    "service-framework/src/syncher/proxyobject.js~objecttype",
    "variable/index.html#static-variable-ObjectType",
    "<span>ObjectType</span> <span class=\"search-result-import-path\">service-framework/src/syncher/ProxyObject.js</span>",
    "variable"
  ],
  [
    "service-framework/src/syncher/syncobject.js~objecttype",
    "variable/index.html#static-variable-ObjectType",
    "<span>ObjectType</span> <span class=\"search-result-import-path\">service-framework/src/syncher/SyncObject.js</span>",
    "variable"
  ],
  [
    "service-framework/src/identity/openidlib.js~openidlib",
    "class/src/identity/OpenIdLib.js~OpenIdLib.html",
    "<span>OpenIdLib</span> <span class=\"search-result-import-path\">service-framework/src/identity/OpenIdLib.js</span>",
    "class"
  ],
  [
    "service-framework/src/bus/pipeline.js~pipeline",
    "class/src/bus/Pipeline.js~Pipeline.html",
    "<span>Pipeline</span> <span class=\"search-result-import-path\">service-framework/src/bus/Pipeline.js</span>",
    "class"
  ],
  [
    "service-framework/src/syncher/syncher.js~syncher",
    "class/src/syncher/Syncher.js~Syncher.html",
    "<span>Syncher</span> <span class=\"search-result-import-path\">service-framework/src/syncher/Syncher.js</span>",
    "class"
  ],
  [
    "service-framework/src/utils/watchingyou.js~watchingyou",
    "class/src/utils/WatchingYou.js~WatchingYou.html",
    "<span>WatchingYou</span> <span class=\"search-result-import-path\">service-framework/src/utils/WatchingYou.js</span>",
    "class"
  ],
  [
    "service-framework/src/utils/utils.js~checkattribute",
    "function/index.html#static-function-checkAttribute",
    "<span>checkAttribute</span> <span class=\"search-result-import-path\">service-framework/src/utils/utils.js</span>",
    "function"
  ],
  [
    "service-framework/src/utils/utils.js~converttouserurl",
    "function/index.html#static-function-convertToUserURL",
    "<span>convertToUserURL</span> <span class=\"search-result-import-path\">service-framework/src/utils/utils.js</span>",
    "function"
  ],
  [
    "service-framework/src/utils/utils.js~deepclone",
    "function/index.html#static-function-deepClone",
    "<span>deepClone</span> <span class=\"search-result-import-path\">service-framework/src/utils/utils.js</span>",
    "function"
  ],
  [
    "service-framework/src/utils/utils.js~divideemail",
    "function/index.html#static-function-divideEmail",
    "<span>divideEmail</span> <span class=\"search-result-import-path\">service-framework/src/utils/utils.js</span>",
    "function"
  ],
  [
    "service-framework/src/utils/utils.js~divideurl",
    "function/index.html#static-function-divideURL",
    "<span>divideURL</span> <span class=\"search-result-import-path\">service-framework/src/utils/utils.js</span>",
    "function"
  ],
  [
    "service-framework/src/utils/utils.js~emptyobject",
    "function/index.html#static-function-emptyObject",
    "<span>emptyObject</span> <span class=\"search-result-import-path\">service-framework/src/utils/utils.js</span>",
    "function"
  ],
  [
    "service-framework/src/utils/utils.js~getuseremailfromurl",
    "function/index.html#static-function-getUserEmailFromURL",
    "<span>getUserEmailFromURL</span> <span class=\"search-result-import-path\">service-framework/src/utils/utils.js</span>",
    "function"
  ],
  [
    "service-framework/src/utils/utils.js~getuserurlfromemail",
    "function/index.html#static-function-getUserURLFromEmail",
    "<span>getUserURLFromEmail</span> <span class=\"search-result-import-path\">service-framework/src/utils/utils.js</span>",
    "function"
  ],
  [
    "service-framework/src/utils/utils.js~parseattributes",
    "function/index.html#static-function-parseAttributes",
    "<span>parseAttributes</span> <span class=\"search-result-import-path\">service-framework/src/utils/utils.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber18",
    "CatalogueDataObjectFactory",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber22",
    "CatalogueDataObjectFactory constructor()",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber24",
    "CatalogueDataObjectFactory constructor() should create a CatalogueDataObject-Factory object without error",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber116",
    "CatalogueDataObjectFactory createCatalogueDataObject()",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber128",
    "CatalogueDataObjectFactory createCatalogueDataObject() should be of type HYPERTY",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber120",
    "CatalogueDataObjectFactory createCatalogueDataObject() should generate CatalogueDataObject of type HypertyDescriptor",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber132",
    "CatalogueDataObjectFactory createCatalogueDataObject() should have valid GUID",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber160",
    "CatalogueDataObjectFactory createHypertyDataObjectSchema()",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber174",
    "CatalogueDataObjectFactory createHypertyDataObjectSchema() should be of type DATA_SCHEMA",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber163",
    "CatalogueDataObjectFactory createHypertyDataObjectSchema() should generate HypertyDataObjectSchema",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber178",
    "CatalogueDataObjectFactory createHypertyDataObjectSchema() should have valid GUID",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber29",
    "CatalogueDataObjectFactory createHypertyDescriptorObject()",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber41",
    "CatalogueDataObjectFactory createHypertyDescriptorObject() should be of type HYPERTY",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber33",
    "CatalogueDataObjectFactory createHypertyDescriptorObject() should generate HypertyDescriptor",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber59",
    "CatalogueDataObjectFactory createHypertyDescriptorObject() should have valid GUID",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber45",
    "CatalogueDataObjectFactory createHypertyDescriptorObject() testing getters/setters (name, type, messageSchema)",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber86",
    "CatalogueDataObjectFactory createHypertyInterceptorObject()",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber97",
    "CatalogueDataObjectFactory createHypertyInterceptorObject() should be of type HYPERTY_INTERCEPTOR",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber89",
    "CatalogueDataObjectFactory createHypertyInterceptorObject() should generate HypertyInterceptorDescriptor",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber101",
    "CatalogueDataObjectFactory createHypertyInterceptorObject() should have valid GUID",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber138",
    "CatalogueDataObjectFactory createHypertyRuntimeDescriptorObject()",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber150",
    "CatalogueDataObjectFactory createHypertyRuntimeDescriptorObject() should be of type HYPERTY_RUNTIME",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber141",
    "CatalogueDataObjectFactory createHypertyRuntimeDescriptorObject() should generate HypertyRuntimeDescriptor",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber154",
    "CatalogueDataObjectFactory createHypertyRuntimeDescriptorObject() should have valid GUID",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber65",
    "CatalogueDataObjectFactory createProtoStubDescriptorObject()",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber76",
    "CatalogueDataObjectFactory createProtoStubDescriptorObject() should be of type PROTOSTUB",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber68",
    "CatalogueDataObjectFactory createProtoStubDescriptorObject() should generate ProtocolStubDescriptor",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber80",
    "CatalogueDataObjectFactory createProtoStubDescriptorObject() should have valid GUID",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber107",
    "CatalogueDataObjectFactory createSourcePackage()",
    "test"
  ],
  [
    "",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html#lineNumber110",
    "CatalogueDataObjectFactory createSourcePackage() should generate SourcePackage",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber9",
    "Discovery",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber226",
    "Discovery constructor()",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber227",
    "Discovery constructor() should create a HypertyDiscovery object without error",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber330",
    "Discovery discoverDataObjectPerURL()",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber331",
    "Discovery discoverDataObjectPerURL() should conclude the advanced search without error",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber312",
    "Discovery discoverDataObjects()",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber313",
    "Discovery discoverDataObjects() should conclude the advanced search without error",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber294",
    "Discovery discoverDataObjectsPerGUID()",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber295",
    "Discovery discoverDataObjectsPerGUID() should conclude the advanced search without error",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber339",
    "Discovery discoverDataObjectsPerName()",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber340",
    "Discovery discoverDataObjectsPerName() should conclude the advanced search without error",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber348",
    "Discovery discoverDataObjectsPerReporter()",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber349",
    "Discovery discoverDataObjectsPerReporter() should conclude the advanced search without error",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber276",
    "Discovery discoverDataObjectsPerUserProfileData()",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber277",
    "Discovery discoverDataObjectsPerUserProfileData() should conclude the advanced search without error",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber303",
    "Discovery discoverHyperties()",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber304",
    "Discovery discoverHyperties() should conclude the advanced search without error",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber285",
    "Discovery discoverHypertiesPerGUID()",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber286",
    "Discovery discoverHypertiesPerGUID() should conclude the advanced search without error",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber267",
    "Discovery discoverHypertiesPerUserProfileData()",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber268",
    "Discovery discoverHypertiesPerUserProfileData() should conclude the advanced search without error",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber258",
    "Discovery discoverHyperty()",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber259",
    "Discovery discoverHyperty() should conclude the advanced search without error",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber321",
    "Discovery discoverHypertyPerURL()",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber322",
    "Discovery discoverHypertyPerURL() should conclude the advanced search without error",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber232",
    "Discovery discoverHypertyPerUser()",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber246",
    "Discovery discoverHypertyPerUser() should return a Promise with an Identity using a given domain",
    "test"
  ],
  [
    "",
    "test-file/test/Discovery.spec.js.html#lineNumber233",
    "Discovery discoverHypertyPerUser() should return a Promise with an Identity using the default domain",
    "test"
  ],
  [
    "",
    "test-file/test/IdentityFactory.spec.js.html#lineNumber11",
    "IdentityFactory",
    "test"
  ],
  [
    "",
    "test-file/test/IdentityFactory.spec.js.html#lineNumber14",
    "IdentityFactory constructor()",
    "test"
  ],
  [
    "",
    "test-file/test/IdentityFactory.spec.js.html#lineNumber15",
    "IdentityFactory constructor() should create an Identity object without error",
    "test"
  ],
  [
    "",
    "test-file/test/IdentityManager.spec.js.html#lineNumber9",
    "IdentityManager",
    "test"
  ],
  [
    "",
    "test-file/test/IdentityManager.spec.js.html#lineNumber30",
    "IdentityManager constructor()",
    "test"
  ],
  [
    "",
    "test-file/test/IdentityManager.spec.js.html#lineNumber31",
    "IdentityManager constructor() should create a identityManager object without error",
    "test"
  ],
  [
    "",
    "test-file/test/IdentityManager.spec.js.html#lineNumber36",
    "IdentityManager discoverUserRegistered()",
    "test"
  ],
  [
    "",
    "test-file/test/IdentityManager.spec.js.html#lineNumber37",
    "IdentityManager discoverUserRegistered() should return a Promise with the identity associated",
    "test"
  ],
  [
    "",
    "test-file/test/IdentityManager.spec.js.html#lineNumber44",
    "IdentityManager discoverUserRegistered() should return a Promise with the identity associated (with optional hyperty field)",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber14",
    "MessageFactory",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber146",
    "MessageFactory addAccessToken()",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber147",
    "MessageFactory addAccessToken() should add asserted identity to the given message",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber156",
    "MessageFactory addIdToken()",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber157",
    "MessageFactory addIdToken() should add asserted identity to the given message",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber136",
    "MessageFactory assertIdentity()",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber137",
    "MessageFactory assertIdentity() should add asserted identity to the given message",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber18",
    "MessageFactory constructor()",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber19",
    "MessageFactory constructor() should create a Message Factory object without error",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber25",
    "MessageFactory createCreateMessageRequest()",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber26",
    "MessageFactory createCreateMessageRequest() should be a Message of Type CREATE",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber57",
    "MessageFactory createDeleteMessageRequest()",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber58",
    "MessageFactory createDeleteMessageRequest() should be a Message of Type DELETE",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber166",
    "MessageFactory createExecuteMessageRequest()",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber168",
    "MessageFactory createExecuteMessageRequest() should create a new Execute Message Request",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber40",
    "MessageFactory createForwardMessageRequest()",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber42",
    "MessageFactory createForwardMessageRequest() should create a new Forward Message Request with a message payload",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber182",
    "MessageFactory createMessageResponse()",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber183",
    "MessageFactory createMessageResponse() should be a Response Message of Type RESPONSE",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber90",
    "MessageFactory createReadMessageRequest()",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber91",
    "MessageFactory createReadMessageRequest() should be a Message of Type READ",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber106",
    "MessageFactory createSubscribeMessageRequest()",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber107",
    "MessageFactory createSubscribeMessageRequest() should be a Message of Type SUBSCRIBE",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber121",
    "MessageFactory createUnSubscribeMessageRequest()",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber122",
    "MessageFactory createUnSubscribeMessageRequest() should be a Message of Type SUBSCRIBE",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber74",
    "MessageFactory createUpdateMessageRequest()",
    "test"
  ],
  [
    "",
    "test-file/test/MessageFactory.spec.js.html#lineNumber75",
    "MessageFactory createUpdateMessageRequest() should be a Message of Type UPDATE",
    "test"
  ],
  [
    "",
    "test-file/test/RuntimeCatalogue.spec.js.html#lineNumber35",
    "Runtime Catalogue",
    "test"
  ],
  [
    "",
    "test-file/test/RuntimeCatalogue.spec.js.html#lineNumber106",
    "Runtime Catalogue should NOT get hyperty",
    "test"
  ],
  [
    "",
    "test-file/test/RuntimeCatalogue.spec.js.html#lineNumber90",
    "Runtime Catalogue should get dataschema descriptor",
    "test"
  ],
  [
    "",
    "test-file/test/RuntimeCatalogue.spec.js.html#lineNumber49",
    "Runtime Catalogue should get hyperty descriptor",
    "test"
  ],
  [
    "",
    "test-file/test/RuntimeCatalogue.spec.js.html#lineNumber66",
    "Runtime Catalogue should get hyperty source code",
    "test"
  ],
  [
    "",
    "test-file/test/RuntimeCatalogue.spec.js.html#lineNumber98",
    "Runtime Catalogue should get idpproxy descriptor",
    "test"
  ],
  [
    "",
    "test-file/test/RuntimeCatalogue.spec.js.html#lineNumber74",
    "Runtime Catalogue should get protostub descriptor",
    "test"
  ],
  [
    "",
    "test-file/test/RuntimeCatalogue.spec.js.html#lineNumber82",
    "Runtime Catalogue should get runtime descriptor",
    "test"
  ],
  [
    "",
    "test-file/test/RuntimeCatalogue.spec.js.html#lineNumber58",
    "Runtime Catalogue should get sourcePackage",
    "test"
  ],
  [
    "",
    "test-file/test/RuntimeCapabilities.spec.js.html#lineNumber17",
    "Runtime Runtime Capabilities",
    "test"
  ],
  [
    "",
    "test-file/test/RuntimeCapabilities.spec.js.html#lineNumber121",
    "Runtime Runtime Capabilities should return a promise with RuntimeCapabilities and save on storageManager",
    "test"
  ],
  [
    "",
    "test-file/test/RuntimeCapabilities.spec.js.html#lineNumber129",
    "Runtime Runtime Capabilities should return if a capability was available",
    "test"
  ],
  [
    "",
    "test-file/test/RuntimeCapabilities.spec.js.html#lineNumber155",
    "Runtime Runtime Capabilities should update the previous capabilites",
    "test"
  ],
  [
    "",
    "test-file/test/StorageManager.spec.js.html#lineNumber7",
    "StorageManager",
    "test"
  ],
  [
    "",
    "test-file/test/StorageManager.spec.js.html#lineNumber79",
    "StorageManager delete",
    "test"
  ],
  [
    "",
    "test-file/test/StorageManager.spec.js.html#lineNumber80",
    "StorageManager delete should remove a value from StorageManager for a given key",
    "test"
  ],
  [
    "",
    "test-file/test/StorageManager.spec.js.html#lineNumber91",
    "StorageManager delete shouldnt remove a value from StorageManager if the given key doesnt exist",
    "test"
  ],
  [
    "",
    "test-file/test/StorageManager.spec.js.html#lineNumber36",
    "StorageManager get",
    "test"
  ],
  [
    "",
    "test-file/test/StorageManager.spec.js.html#lineNumber37",
    "StorageManager get should get the value for a given key",
    "test"
  ],
  [
    "",
    "test-file/test/StorageManager.spec.js.html#lineNumber49",
    "StorageManager get should return undefined if no object with the given key exists",
    "test"
  ],
  [
    "",
    "test-file/test/StorageManager.spec.js.html#lineNumber58",
    "StorageManager getVersion",
    "test"
  ],
  [
    "",
    "test-file/test/StorageManager.spec.js.html#lineNumber59",
    "StorageManager getVersion should get the value version for a given key",
    "test"
  ],
  [
    "",
    "test-file/test/StorageManager.spec.js.html#lineNumber70",
    "StorageManager getVersion should get undefined if no object with the given key exists",
    "test"
  ],
  [
    "",
    "test-file/test/StorageManager.spec.js.html#lineNumber15",
    "StorageManager set",
    "test"
  ],
  [
    "",
    "test-file/test/StorageManager.spec.js.html#lineNumber25",
    "StorageManager set should replace the value for a given key-version tuple if it exists",
    "test"
  ],
  [
    "",
    "test-file/test/StorageManager.spec.js.html#lineNumber17",
    "StorageManager set should set the value for a given key-version tuple",
    "test"
  ],
  [
    "",
    "test-file/test/Sync.spec.js.html#lineNumber11",
    "The Object.Observer and Array.Observer",
    "test"
  ],
  [
    "",
    "test-file/test/Sync.spec.js.html#lineNumber13",
    "The Object.Observer and Array.Observer should use SyncObject",
    "test"
  ],
  [
    "",
    "test-file/test/Sync.spec.js.html#lineNumber50",
    "The Object.Observer and Array.Observer should use SyncObject observe",
    "test"
  ],
  [
    "",
    "test-file/test/JsonSchemaValidation.spec.js.html#lineNumber69",
    "adding new schema",
    "test"
  ],
  [
    "",
    "test-file/test/JsonSchemaValidation.spec.js.html#lineNumber70",
    "adding new schema should add a new schema",
    "test"
  ],
  [
    "",
    "test-file/test/JsonSchemaValidation.spec.js.html#lineNumber52",
    "schema validation of good Apple",
    "test"
  ],
  [
    "",
    "test-file/test/JsonSchemaValidation.spec.js.html#lineNumber53",
    "schema validation of good Apple good Apple should be good",
    "test"
  ],
  [
    "",
    "test-file/test/JsonSchemaValidation.spec.js.html#lineNumber54",
    "schema validation of good Apple good Apple should be good should return false instead of true",
    "test"
  ],
  [
    "src/bus/bus.js",
    "file/src/bus/Bus.js.html",
    "src/bus/Bus.js",
    "file"
  ],
  [
    "src/bus/bus.js~bus#addlistener",
    "class/src/bus/Bus.js~Bus.html#instance-method-addListener",
    "src/bus/Bus.js~Bus#addListener",
    "method"
  ],
  [
    "src/bus/bus.js~bus#addresponselistener",
    "class/src/bus/Bus.js~Bus.html#instance-method-addResponseListener",
    "src/bus/Bus.js~Bus#addResponseListener",
    "method"
  ],
  [
    "src/bus/bus.js~bus#bind",
    "class/src/bus/Bus.js~Bus.html#instance-method-bind",
    "src/bus/Bus.js~Bus#bind",
    "method"
  ],
  [
    "src/bus/bus.js~bus#constructor",
    "class/src/bus/Bus.js~Bus.html#instance-constructor-constructor",
    "src/bus/Bus.js~Bus#constructor",
    "method"
  ],
  [
    "src/bus/bus.js~bus#postmessage",
    "class/src/bus/Bus.js~Bus.html#instance-method-postMessage",
    "src/bus/Bus.js~Bus#postMessage",
    "method"
  ],
  [
    "src/bus/bus.js~bus#removealllistenersof",
    "class/src/bus/Bus.js~Bus.html#instance-method-removeAllListenersOf",
    "src/bus/Bus.js~Bus#removeAllListenersOf",
    "method"
  ],
  [
    "src/bus/bus.js~bus#removeresponselistener",
    "class/src/bus/Bus.js~Bus.html#instance-method-removeResponseListener",
    "src/bus/Bus.js~Bus#removeResponseListener",
    "method"
  ],
  [
    "src/bus/messagebus.js",
    "file/src/bus/MessageBus.js.html",
    "src/bus/MessageBus.js",
    "file"
  ],
  [
    "src/bus/messagebus.js~messagebus#addforward",
    "class/src/bus/MessageBus.js~MessageBus.html#instance-method-addForward",
    "src/bus/MessageBus.js~MessageBus#addForward",
    "method"
  ],
  [
    "src/bus/messagebus.js~messagebus#addpublish",
    "class/src/bus/MessageBus.js~MessageBus.html#instance-method-addPublish",
    "src/bus/MessageBus.js~MessageBus#addPublish",
    "method"
  ],
  [
    "src/bus/messagebus.js~messagebus#constructor",
    "class/src/bus/MessageBus.js~MessageBus.html#instance-constructor-constructor",
    "src/bus/MessageBus.js~MessageBus#constructor",
    "method"
  ],
  [
    "src/bus/messagebus.js~messagebus#forward",
    "class/src/bus/MessageBus.js~MessageBus.html#instance-method-forward",
    "src/bus/MessageBus.js~MessageBus#forward",
    "method"
  ],
  [
    "src/bus/messagebus.js~messagebus#pipeline",
    "class/src/bus/MessageBus.js~MessageBus.html#instance-get-pipeline",
    "src/bus/MessageBus.js~MessageBus#pipeline",
    "member"
  ],
  [
    "src/bus/messagebus.js~messagebus#postmessage",
    "class/src/bus/MessageBus.js~MessageBus.html#instance-method-postMessage",
    "src/bus/MessageBus.js~MessageBus#postMessage",
    "method"
  ],
  [
    "src/bus/minibus.js",
    "file/src/bus/MiniBus.js.html",
    "src/bus/MiniBus.js",
    "file"
  ],
  [
    "src/bus/minibus.js~minibus#constructor",
    "class/src/bus/MiniBus.js~MiniBus.html#instance-constructor-constructor",
    "src/bus/MiniBus.js~MiniBus#constructor",
    "method"
  ],
  [
    "src/bus/minibus.js~minibus#postmessage",
    "class/src/bus/MiniBus.js~MiniBus.html#instance-method-postMessage",
    "src/bus/MiniBus.js~MiniBus#postMessage",
    "method"
  ],
  [
    "src/bus/pipeline.js",
    "file/src/bus/Pipeline.js.html",
    "src/bus/Pipeline.js",
    "file"
  ],
  [
    "src/bus/pipeline.js~pipeline#constructor",
    "class/src/bus/Pipeline.js~Pipeline.html#instance-constructor-constructor",
    "src/bus/Pipeline.js~Pipeline#constructor",
    "method"
  ],
  [
    "src/bus/pipeline.js~pipeline#process",
    "class/src/bus/Pipeline.js~Pipeline.html#instance-method-process",
    "src/bus/Pipeline.js~Pipeline#process",
    "method"
  ],
  [
    "src/discovery/discovery.js",
    "file/src/discovery/Discovery.js.html",
    "src/discovery/Discovery.js",
    "file"
  ],
  [
    "src/discovery/discovery.js~discovery#constructor",
    "class/src/discovery/Discovery.js~Discovery.html#instance-constructor-constructor",
    "src/discovery/Discovery.js~Discovery#constructor",
    "method"
  ],
  [
    "src/discovery/discovery.js~discovery#discoverdataobject",
    "class/src/discovery/Discovery.js~Discovery.html#instance-method-discoverDataObject",
    "src/discovery/Discovery.js~Discovery#discoverDataObject",
    "method"
  ],
  [
    "src/discovery/discovery.js~discovery#discoverdataobjectperurl",
    "class/src/discovery/Discovery.js~Discovery.html#instance-method-discoverDataObjectPerURL",
    "src/discovery/Discovery.js~Discovery#discoverDataObjectPerURL",
    "method"
  ],
  [
    "src/discovery/discovery.js~discovery#discoverdataobjects",
    "class/src/discovery/Discovery.js~Discovery.html#instance-method-discoverDataObjects",
    "src/discovery/Discovery.js~Discovery#discoverDataObjects",
    "method"
  ],
  [
    "src/discovery/discovery.js~discovery#discoverdataobjectsperguid",
    "class/src/discovery/Discovery.js~Discovery.html#instance-method-discoverDataObjectsPerGUID",
    "src/discovery/Discovery.js~Discovery#discoverDataObjectsPerGUID",
    "method"
  ],
  [
    "src/discovery/discovery.js~discovery#discoverdataobjectspername",
    "class/src/discovery/Discovery.js~Discovery.html#instance-method-discoverDataObjectsPerName",
    "src/discovery/Discovery.js~Discovery#discoverDataObjectsPerName",
    "method"
  ],
  [
    "src/discovery/discovery.js~discovery#discoverdataobjectsperreporter",
    "class/src/discovery/Discovery.js~Discovery.html#instance-method-discoverDataObjectsPerReporter",
    "src/discovery/Discovery.js~Discovery#discoverDataObjectsPerReporter",
    "method"
  ],
  [
    "src/discovery/discovery.js~discovery#discoverdataobjectsperuserprofiledata",
    "class/src/discovery/Discovery.js~Discovery.html#instance-method-discoverDataObjectsPerUserProfileData",
    "src/discovery/Discovery.js~Discovery#discoverDataObjectsPerUserProfileData",
    "method"
  ],
  [
    "src/discovery/discovery.js~discovery#discoverhyperties",
    "class/src/discovery/Discovery.js~Discovery.html#instance-method-discoverHyperties",
    "src/discovery/Discovery.js~Discovery#discoverHyperties",
    "method"
  ],
  [
    "src/discovery/discovery.js~discovery#discoverhypertiesperguid",
    "class/src/discovery/Discovery.js~Discovery.html#instance-method-discoverHypertiesPerGUID",
    "src/discovery/Discovery.js~Discovery#discoverHypertiesPerGUID",
    "method"
  ],
  [
    "src/discovery/discovery.js~discovery#discoverhypertiesperuser",
    "class/src/discovery/Discovery.js~Discovery.html#instance-method-discoverHypertiesPerUser",
    "src/discovery/Discovery.js~Discovery#discoverHypertiesPerUser",
    "method"
  ],
  [
    "src/discovery/discovery.js~discovery#discoverhypertiesperuserprofiledata",
    "class/src/discovery/Discovery.js~Discovery.html#instance-method-discoverHypertiesPerUserProfileData",
    "src/discovery/Discovery.js~Discovery#discoverHypertiesPerUserProfileData",
    "method"
  ],
  [
    "src/discovery/discovery.js~discovery#discoverhyperty",
    "class/src/discovery/Discovery.js~Discovery.html#instance-method-discoverHyperty",
    "src/discovery/Discovery.js~Discovery#discoverHyperty",
    "method"
  ],
  [
    "src/discovery/discovery.js~discovery#discoverhypertyperurl",
    "class/src/discovery/Discovery.js~Discovery.html#instance-method-discoverHypertyPerURL",
    "src/discovery/Discovery.js~Discovery#discoverHypertyPerURL",
    "method"
  ],
  [
    "src/discovery/discovery.js~discovery#discoverhypertyperuser",
    "class/src/discovery/Discovery.js~Discovery.html#instance-method-discoverHypertyPerUser",
    "src/discovery/Discovery.js~Discovery#discoverHypertyPerUser",
    "method"
  ],
  [
    "src/identity/crypto.js",
    "file/src/identity/Crypto.js.html",
    "src/identity/Crypto.js",
    "file"
  ],
  [
    "src/identity/crypto.js~crypto#concatpmswithrandoms",
    "class/src/identity/Crypto.js~Crypto.html#instance-method-concatPMSwithRandoms",
    "src/identity/Crypto.js~Crypto#concatPMSwithRandoms",
    "method"
  ],
  [
    "src/identity/crypto.js~crypto#constructor",
    "class/src/identity/Crypto.js~Crypto.html#instance-constructor-constructor",
    "src/identity/Crypto.js~Crypto#constructor",
    "method"
  ],
  [
    "src/identity/crypto.js~crypto#decode",
    "class/src/identity/Crypto.js~Crypto.html#instance-method-decode",
    "src/identity/Crypto.js~Crypto#decode",
    "method"
  ],
  [
    "src/identity/crypto.js~crypto#decryptaes",
    "class/src/identity/Crypto.js~Crypto.html#instance-method-decryptAES",
    "src/identity/Crypto.js~Crypto#decryptAES",
    "method"
  ],
  [
    "src/identity/crypto.js~crypto#decryptrsa",
    "class/src/identity/Crypto.js~Crypto.html#instance-method-decryptRSA",
    "src/identity/Crypto.js~Crypto#decryptRSA",
    "method"
  ],
  [
    "src/identity/crypto.js~crypto#encode",
    "class/src/identity/Crypto.js~Crypto.html#instance-method-encode",
    "src/identity/Crypto.js~Crypto#encode",
    "method"
  ],
  [
    "src/identity/crypto.js~crypto#encryptaes",
    "class/src/identity/Crypto.js~Crypto.html#instance-method-encryptAES",
    "src/identity/Crypto.js~Crypto#encryptAES",
    "method"
  ],
  [
    "src/identity/crypto.js~crypto#encryptrsa",
    "class/src/identity/Crypto.js~Crypto.html#instance-method-encryptRSA",
    "src/identity/Crypto.js~Crypto#encryptRSA",
    "method"
  ],
  [
    "src/identity/crypto.js~crypto#generateiv",
    "class/src/identity/Crypto.js~Crypto.html#instance-method-generateIV",
    "src/identity/Crypto.js~Crypto#generateIV",
    "method"
  ],
  [
    "src/identity/crypto.js~crypto#generatekeys",
    "class/src/identity/Crypto.js~Crypto.html#instance-method-generateKeys",
    "src/identity/Crypto.js~Crypto#generateKeys",
    "method"
  ],
  [
    "src/identity/crypto.js~crypto#generatemastersecret",
    "class/src/identity/Crypto.js~Crypto.html#instance-method-generateMasterSecret",
    "src/identity/Crypto.js~Crypto#generateMasterSecret",
    "method"
  ],
  [
    "src/identity/crypto.js~crypto#generatepms",
    "class/src/identity/Crypto.js~Crypto.html#instance-method-generatePMS",
    "src/identity/Crypto.js~Crypto#generatePMS",
    "method"
  ],
  [
    "src/identity/crypto.js~crypto#generatersakeypair",
    "class/src/identity/Crypto.js~Crypto.html#instance-method-generateRSAKeyPair",
    "src/identity/Crypto.js~Crypto#generateRSAKeyPair",
    "method"
  ],
  [
    "src/identity/crypto.js~crypto#generaterandom",
    "class/src/identity/Crypto.js~Crypto.html#instance-method-generateRandom",
    "src/identity/Crypto.js~Crypto#generateRandom",
    "method"
  ],
  [
    "src/identity/crypto.js~crypto#hashhmac",
    "class/src/identity/Crypto.js~Crypto.html#instance-method-hashHMAC",
    "src/identity/Crypto.js~Crypto#hashHMAC",
    "method"
  ],
  [
    "src/identity/crypto.js~crypto#signrsa",
    "class/src/identity/Crypto.js~Crypto.html#instance-method-signRSA",
    "src/identity/Crypto.js~Crypto#signRSA",
    "method"
  ],
  [
    "src/identity/crypto.js~crypto#verifyhmac",
    "class/src/identity/Crypto.js~Crypto.html#instance-method-verifyHMAC",
    "src/identity/Crypto.js~Crypto#verifyHMAC",
    "method"
  ],
  [
    "src/identity/crypto.js~crypto#verifyrsa",
    "class/src/identity/Crypto.js~Crypto.html#instance-method-verifyRSA",
    "src/identity/Crypto.js~Crypto#verifyRSA",
    "method"
  ],
  [
    "src/identity/guifake.js",
    "file/src/identity/GuiFake.js.html",
    "src/identity/GuiFake.js",
    "file"
  ],
  [
    "src/identity/guifake.js~guifake#constructor",
    "class/src/identity/GuiFake.js~GuiFake.html#instance-constructor-constructor",
    "src/identity/GuiFake.js~GuiFake#constructor",
    "method"
  ],
  [
    "src/identity/identity.js",
    "file/src/identity/Identity.js.html",
    "src/identity/Identity.js",
    "file"
  ],
  [
    "src/identity/identity.js~identity#addidassertion",
    "class/src/identity/Identity.js~Identity.html#instance-method-addIdAssertion",
    "src/identity/Identity.js~Identity#addIdAssertion",
    "method"
  ],
  [
    "src/identity/identity.js~identity#addidentity",
    "class/src/identity/Identity.js~Identity.html#instance-method-addIdentity",
    "src/identity/Identity.js~Identity#addIdentity",
    "method"
  ],
  [
    "src/identity/identity.js~identity#constructor",
    "class/src/identity/Identity.js~Identity.html#instance-constructor-constructor",
    "src/identity/Identity.js~Identity#constructor",
    "method"
  ],
  [
    "src/identity/identitymodule.js",
    "file/src/identity/IdentityModule.js.html",
    "src/identity/IdentityModule.js",
    "file"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#addguilisteners",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-addGUIListeners",
    "src/identity/IdentityModule.js~IdentityModule#addGUIListeners",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#callgeneratemethods",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-callGenerateMethods",
    "src/identity/IdentityModule.js~IdentityModule#callGenerateMethods",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#callidentitymodulefunc",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-callIdentityModuleFunc",
    "src/identity/IdentityModule.js~IdentityModule#callIdentityModuleFunc",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#constructor",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-constructor-constructor",
    "src/identity/IdentityModule.js~IdentityModule#constructor",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#decryptdataobject",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-decryptDataObject",
    "src/identity/IdentityModule.js~IdentityModule#decryptDataObject",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#decryptmessage",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-decryptMessage",
    "src/identity/IdentityModule.js~IdentityModule#decryptMessage",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#deleteidentity",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-deleteIdentity",
    "src/identity/IdentityModule.js~IdentityModule#deleteIdentity",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#deploygui",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-deployGUI",
    "src/identity/IdentityModule.js~IdentityModule#deployGUI",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#domutualauthentication",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-doMutualAuthentication",
    "src/identity/IdentityModule.js~IdentityModule#doMutualAuthentication",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#encryptdataobject",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-encryptDataObject",
    "src/identity/IdentityModule.js~IdentityModule#encryptDataObject",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#encryptmessage",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-encryptMessage",
    "src/identity/IdentityModule.js~IdentityModule#encryptMessage",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#generateassertion",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-generateAssertion",
    "src/identity/IdentityModule.js~IdentityModule#generateAssertion",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#generateselectedidentity",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-generateSelectedIdentity",
    "src/identity/IdentityModule.js~IdentityModule#generateSelectedIdentity",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#getaccesstoken",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-getAccessToken",
    "src/identity/IdentityModule.js~IdentityModule#getAccessToken",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#getcurrentidentity",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-getCurrentIdentity",
    "src/identity/IdentityModule.js~IdentityModule#getCurrentIdentity",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#getexistingvalidtoken",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-getExistingValidToken",
    "src/identity/IdentityModule.js~IdentityModule#getExistingValidToken",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#getidtoken",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-getIdToken",
    "src/identity/IdentityModule.js~IdentityModule#getIdToken",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#getidentities",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-getIdentities",
    "src/identity/IdentityModule.js~IdentityModule#getIdentities",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#getidentitiestochoose",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-getIdentitiesToChoose",
    "src/identity/IdentityModule.js~IdentityModule#getIdentitiesToChoose",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#getidentity",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-getIdentity",
    "src/identity/IdentityModule.js~IdentityModule#getIdentity",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#getidentityassertion",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-getIdentityAssertion",
    "src/identity/IdentityModule.js~IdentityModule#getIdentityAssertion",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#gettoken",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-getToken",
    "src/identity/IdentityModule.js~IdentityModule#getToken",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#getusersids",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-getUsersIDs",
    "src/identity/IdentityModule.js~IdentityModule#getUsersIDs",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#loginselectedidentity",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-loginSelectedIdentity",
    "src/identity/IdentityModule.js~IdentityModule#loginSelectedIdentity",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#messagebus",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-get-messageBus",
    "src/identity/IdentityModule.js~IdentityModule#messageBus",
    "member"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#messagebus",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-set-messageBus",
    "src/identity/IdentityModule.js~IdentityModule#messageBus",
    "member"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#registry",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-set-registry",
    "src/identity/IdentityModule.js~IdentityModule#registry",
    "member"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#registry",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-get-registry",
    "src/identity/IdentityModule.js~IdentityModule#registry",
    "member"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#requestidentitytogui",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-requestIdentityToGUI",
    "src/identity/IdentityModule.js~IdentityModule#requestIdentityToGUI",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#selectidentityforhyperty",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-selectIdentityForHyperty",
    "src/identity/IdentityModule.js~IdentityModule#selectIdentityForHyperty",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#selectidentityfromgui",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-selectIdentityFromGUI",
    "src/identity/IdentityModule.js~IdentityModule#selectIdentityFromGUI",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#sendgeneratemessage",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-sendGenerateMessage",
    "src/identity/IdentityModule.js~IdentityModule#sendGenerateMessage",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#setcurrentidentity",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-setCurrentIdentity",
    "src/identity/IdentityModule.js~IdentityModule#setCurrentIdentity",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#storeidentity",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-storeIdentity",
    "src/identity/IdentityModule.js~IdentityModule#storeIdentity",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#unregisteridentity",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-unregisterIdentity",
    "src/identity/IdentityModule.js~IdentityModule#unregisterIdentity",
    "method"
  ],
  [
    "src/identity/identitymodule.js~identitymodule#validateassertion",
    "class/src/identity/IdentityModule.js~IdentityModule.html#instance-method-validateAssertion",
    "src/identity/IdentityModule.js~IdentityModule#validateAssertion",
    "method"
  ],
  [
    "src/identity/openidlib.js",
    "file/src/identity/OpenIdLib.js.html",
    "src/identity/OpenIdLib.js",
    "file"
  ],
  [
    "src/identity/openidlib.js~openidlib#constructor",
    "class/src/identity/OpenIdLib.js~OpenIdLib.html#instance-constructor-constructor",
    "src/identity/OpenIdLib.js~OpenIdLib#constructor",
    "method"
  ],
  [
    "src/identity/openidlib.js~openidlib#getinfotoken",
    "class/src/identity/OpenIdLib.js~OpenIdLib.html#instance-method-getInfoToken",
    "src/identity/OpenIdLib.js~OpenIdLib#getInfoToken",
    "method"
  ],
  [
    "src/identity/openidlib.js~openidlib#openpopup",
    "class/src/identity/OpenIdLib.js~OpenIdLib.html#instance-method-openPopup",
    "src/identity/OpenIdLib.js~OpenIdLib#openPopup",
    "method"
  ],
  [
    "src/identity/openidlib.js~openidlib#validatetoken",
    "class/src/identity/OpenIdLib.js~OpenIdLib.html#instance-method-validateToken",
    "src/identity/OpenIdLib.js~OpenIdLib#validateToken",
    "method"
  ],
  [
    "src/syncher/dataobject.js",
    "file/src/syncher/DataObject.js.html",
    "src/syncher/DataObject.js",
    "file"
  ],
  [
    "src/syncher/dataobject.js~dataobject#addchild",
    "class/src/syncher/DataObject.js~DataObject.html#instance-method-addChild",
    "src/syncher/DataObject.js~DataObject#addChild",
    "method"
  ],
  [
    "src/syncher/dataobject.js~dataobject#childrens",
    "class/src/syncher/DataObject.js~DataObject.html#instance-get-childrens",
    "src/syncher/DataObject.js~DataObject#childrens",
    "member"
  ],
  [
    "src/syncher/dataobject.js~dataobject#data",
    "class/src/syncher/DataObject.js~DataObject.html#instance-get-data",
    "src/syncher/DataObject.js~DataObject#data",
    "member"
  ],
  [
    "src/syncher/dataobject.js~dataobject#metadata",
    "class/src/syncher/DataObject.js~DataObject.html#instance-get-metadata",
    "src/syncher/DataObject.js~DataObject#metadata",
    "member"
  ],
  [
    "src/syncher/dataobject.js~dataobject#onaddchild",
    "class/src/syncher/DataObject.js~DataObject.html#instance-method-onAddChild",
    "src/syncher/DataObject.js~DataObject#onAddChild",
    "method"
  ],
  [
    "src/syncher/dataobject.js~dataobject#resumechildrens",
    "class/src/syncher/DataObject.js~DataObject.html#instance-method-resumeChildrens",
    "src/syncher/DataObject.js~DataObject#resumeChildrens",
    "method"
  ],
  [
    "src/syncher/dataobject.js~dataobject#schema",
    "class/src/syncher/DataObject.js~DataObject.html#instance-get-schema",
    "src/syncher/DataObject.js~DataObject#schema",
    "member"
  ],
  [
    "src/syncher/dataobject.js~dataobject#status",
    "class/src/syncher/DataObject.js~DataObject.html#instance-get-status",
    "src/syncher/DataObject.js~DataObject#status",
    "member"
  ],
  [
    "src/syncher/dataobject.js~dataobject#url",
    "class/src/syncher/DataObject.js~DataObject.html#instance-get-url",
    "src/syncher/DataObject.js~DataObject#url",
    "member"
  ],
  [
    "src/syncher/dataobjectchild.js",
    "file/src/syncher/DataObjectChild.js.html",
    "src/syncher/DataObjectChild.js",
    "file"
  ],
  [
    "src/syncher/dataobjectchild.js~dataobjectchild#childid",
    "class/src/syncher/DataObjectChild.js~DataObjectChild.html#instance-get-childId",
    "src/syncher/DataObjectChild.js~DataObjectChild#childId",
    "member"
  ],
  [
    "src/syncher/dataobjectchild.js~dataobjectchild#data",
    "class/src/syncher/DataObjectChild.js~DataObjectChild.html#instance-get-data",
    "src/syncher/DataObjectChild.js~DataObjectChild#data",
    "member"
  ],
  [
    "src/syncher/dataobjectchild.js~dataobjectchild#delete",
    "class/src/syncher/DataObjectChild.js~DataObjectChild.html#instance-method-delete",
    "src/syncher/DataObjectChild.js~DataObjectChild#delete",
    "method"
  ],
  [
    "src/syncher/dataobjectchild.js~dataobjectchild#identity",
    "class/src/syncher/DataObjectChild.js~DataObjectChild.html#instance-get-identity",
    "src/syncher/DataObjectChild.js~DataObjectChild#identity",
    "member"
  ],
  [
    "src/syncher/dataobjectchild.js~dataobjectchild#identity",
    "class/src/syncher/DataObjectChild.js~DataObjectChild.html#instance-set-identity",
    "src/syncher/DataObjectChild.js~DataObjectChild#identity",
    "member"
  ],
  [
    "src/syncher/dataobjectchild.js~dataobjectchild#metadata",
    "class/src/syncher/DataObjectChild.js~DataObjectChild.html#instance-get-metadata",
    "src/syncher/DataObjectChild.js~DataObjectChild#metadata",
    "member"
  ],
  [
    "src/syncher/dataobjectchild.js~dataobjectchild#onchange",
    "class/src/syncher/DataObjectChild.js~DataObjectChild.html#instance-method-onChange",
    "src/syncher/DataObjectChild.js~DataObjectChild#onChange",
    "method"
  ],
  [
    "src/syncher/dataobjectchild.js~dataobjectchild#onresponse",
    "class/src/syncher/DataObjectChild.js~DataObjectChild.html#instance-method-onResponse",
    "src/syncher/DataObjectChild.js~DataObjectChild#onResponse",
    "method"
  ],
  [
    "src/syncher/dataobjectobserver.js",
    "file/src/syncher/DataObjectObserver.js.html",
    "src/syncher/DataObjectObserver.js",
    "file"
  ],
  [
    "src/syncher/dataobjectobserver.js~dataobjectobserver#delete",
    "class/src/syncher/DataObjectObserver.js~DataObjectObserver.html#instance-method-delete",
    "src/syncher/DataObjectObserver.js~DataObjectObserver#delete",
    "method"
  ],
  [
    "src/syncher/dataobjectobserver.js~dataobjectobserver#onchange",
    "class/src/syncher/DataObjectObserver.js~DataObjectObserver.html#instance-method-onChange",
    "src/syncher/DataObjectObserver.js~DataObjectObserver#onChange",
    "method"
  ],
  [
    "src/syncher/dataobjectobserver.js~dataobjectobserver#sync",
    "class/src/syncher/DataObjectObserver.js~DataObjectObserver.html#instance-method-sync",
    "src/syncher/DataObjectObserver.js~DataObjectObserver#sync",
    "method"
  ],
  [
    "src/syncher/dataobjectobserver.js~dataobjectobserver#unsubscribe",
    "class/src/syncher/DataObjectObserver.js~DataObjectObserver.html#instance-method-unsubscribe",
    "src/syncher/DataObjectObserver.js~DataObjectObserver#unsubscribe",
    "method"
  ],
  [
    "src/syncher/dataobjectreporter.js",
    "file/src/syncher/DataObjectReporter.js.html",
    "src/syncher/DataObjectReporter.js",
    "file"
  ],
  [
    "src/syncher/dataobjectreporter.js~dataobjectreporter#delete",
    "class/src/syncher/DataObjectReporter.js~DataObjectReporter.html#instance-method-delete",
    "src/syncher/DataObjectReporter.js~DataObjectReporter#delete",
    "method"
  ],
  [
    "src/syncher/dataobjectreporter.js~dataobjectreporter#inviteobservers",
    "class/src/syncher/DataObjectReporter.js~DataObjectReporter.html#instance-method-inviteObservers",
    "src/syncher/DataObjectReporter.js~DataObjectReporter#inviteObservers",
    "method"
  ],
  [
    "src/syncher/dataobjectreporter.js~dataobjectreporter#onread",
    "class/src/syncher/DataObjectReporter.js~DataObjectReporter.html#instance-method-onRead",
    "src/syncher/DataObjectReporter.js~DataObjectReporter#onRead",
    "method"
  ],
  [
    "src/syncher/dataobjectreporter.js~dataobjectreporter#onresponse",
    "class/src/syncher/DataObjectReporter.js~DataObjectReporter.html#instance-method-onResponse",
    "src/syncher/DataObjectReporter.js~DataObjectReporter#onResponse",
    "method"
  ],
  [
    "src/syncher/dataobjectreporter.js~dataobjectreporter#onsubscription",
    "class/src/syncher/DataObjectReporter.js~DataObjectReporter.html#instance-method-onSubscription",
    "src/syncher/DataObjectReporter.js~DataObjectReporter#onSubscription",
    "method"
  ],
  [
    "src/syncher/dataobjectreporter.js~dataobjectreporter#subscriptions",
    "class/src/syncher/DataObjectReporter.js~DataObjectReporter.html#instance-get-subscriptions",
    "src/syncher/DataObjectReporter.js~DataObjectReporter#subscriptions",
    "member"
  ],
  [
    "src/syncher/dataprovisional.js",
    "file/src/syncher/DataProvisional.js.html",
    "src/syncher/DataProvisional.js",
    "file"
  ],
  [
    "src/syncher/proxyobject.js",
    "file/src/syncher/ProxyObject.js.html",
    "src/syncher/ProxyObject.js",
    "file"
  ],
  [
    "src/syncher/syncobject.js",
    "file/src/syncher/SyncObject.js.html",
    "src/syncher/SyncObject.js",
    "file"
  ],
  [
    "src/syncher/syncher.js",
    "file/src/syncher/Syncher.js.html",
    "src/syncher/Syncher.js",
    "file"
  ],
  [
    "src/syncher/syncher.js~syncher#constructor",
    "class/src/syncher/Syncher.js~Syncher.html#instance-constructor-constructor",
    "src/syncher/Syncher.js~Syncher#constructor",
    "method"
  ],
  [
    "src/syncher/syncher.js~syncher#create",
    "class/src/syncher/Syncher.js~Syncher.html#instance-method-create",
    "src/syncher/Syncher.js~Syncher#create",
    "method"
  ],
  [
    "src/syncher/syncher.js~syncher#observers",
    "class/src/syncher/Syncher.js~Syncher.html#instance-get-observers",
    "src/syncher/Syncher.js~Syncher#observers",
    "member"
  ],
  [
    "src/syncher/syncher.js~syncher#onnotification",
    "class/src/syncher/Syncher.js~Syncher.html#instance-method-onNotification",
    "src/syncher/Syncher.js~Syncher#onNotification",
    "method"
  ],
  [
    "src/syncher/syncher.js~syncher#onobserversresume",
    "class/src/syncher/Syncher.js~Syncher.html#instance-method-onObserversResume",
    "src/syncher/Syncher.js~Syncher#onObserversResume",
    "method"
  ],
  [
    "src/syncher/syncher.js~syncher#onreportersresume",
    "class/src/syncher/Syncher.js~Syncher.html#instance-method-onReportersResume",
    "src/syncher/Syncher.js~Syncher#onReportersResume",
    "method"
  ],
  [
    "src/syncher/syncher.js~syncher#owner",
    "class/src/syncher/Syncher.js~Syncher.html#instance-get-owner",
    "src/syncher/Syncher.js~Syncher#owner",
    "member"
  ],
  [
    "src/syncher/syncher.js~syncher#read",
    "class/src/syncher/Syncher.js~Syncher.html#instance-method-read",
    "src/syncher/Syncher.js~Syncher#read",
    "method"
  ],
  [
    "src/syncher/syncher.js~syncher#reporters",
    "class/src/syncher/Syncher.js~Syncher.html#instance-get-reporters",
    "src/syncher/Syncher.js~Syncher#reporters",
    "member"
  ],
  [
    "src/syncher/syncher.js~syncher#resumeobservers",
    "class/src/syncher/Syncher.js~Syncher.html#instance-method-resumeObservers",
    "src/syncher/Syncher.js~Syncher#resumeObservers",
    "method"
  ],
  [
    "src/syncher/syncher.js~syncher#resumereporters",
    "class/src/syncher/Syncher.js~Syncher.html#instance-method-resumeReporters",
    "src/syncher/Syncher.js~Syncher#resumeReporters",
    "method"
  ],
  [
    "src/syncher/syncher.js~syncher#subscribe",
    "class/src/syncher/Syncher.js~Syncher.html#instance-method-subscribe",
    "src/syncher/Syncher.js~Syncher#subscribe",
    "method"
  ],
  [
    "src/utils/eventemitter.js",
    "file/src/utils/EventEmitter.js.html",
    "src/utils/EventEmitter.js",
    "file"
  ],
  [
    "src/utils/eventemitter.js~eventemitter#addeventlistener",
    "class/src/utils/EventEmitter.js~EventEmitter.html#instance-method-addEventListener",
    "src/utils/EventEmitter.js~EventEmitter#addEventListener",
    "method"
  ],
  [
    "src/utils/eventemitter.js~eventemitter#trigger",
    "class/src/utils/EventEmitter.js~EventEmitter.html#instance-method-trigger",
    "src/utils/EventEmitter.js~EventEmitter#trigger",
    "method"
  ],
  [
    "src/utils/watchingyou.js",
    "file/src/utils/WatchingYou.js.html",
    "src/utils/WatchingYou.js",
    "file"
  ],
  [
    "src/utils/watchingyou.js~watchingyou#constructor",
    "class/src/utils/WatchingYou.js~WatchingYou.html#instance-constructor-constructor",
    "src/utils/WatchingYou.js~WatchingYou#constructor",
    "method"
  ],
  [
    "src/utils/watchingyou.js~watchingyou#observe",
    "class/src/utils/WatchingYou.js~WatchingYou.html#instance-method-observe",
    "src/utils/WatchingYou.js~WatchingYou#observe",
    "method"
  ],
  [
    "src/utils/watchingyou.js~watchingyou#watch",
    "class/src/utils/WatchingYou.js~WatchingYou.html#instance-method-watch",
    "src/utils/WatchingYou.js~WatchingYou#watch",
    "method"
  ],
  [
    "src/utils/utils.js",
    "file/src/utils/utils.js.html",
    "src/utils/utils.js",
    "file"
  ],
  [
    "src/utils/utils.js~divideurl",
    "typedef/index.html#static-typedef-divideURL",
    "src/utils/utils.js~divideURL",
    "typedef"
  ],
  [
    "test/cataloguedataobjectfactory.spec.js",
    "test-file/test/CatalogueDataObjectFactory.spec.js.html",
    "test/CatalogueDataObjectFactory.spec.js",
    "testFile"
  ],
  [
    "test/discovery.spec.js",
    "test-file/test/Discovery.spec.js.html",
    "test/Discovery.spec.js",
    "testFile"
  ],
  [
    "test/identityfactory.spec.js",
    "test-file/test/IdentityFactory.spec.js.html",
    "test/IdentityFactory.spec.js",
    "testFile"
  ],
  [
    "test/identitymanager.spec.js",
    "test-file/test/IdentityManager.spec.js.html",
    "test/IdentityManager.spec.js",
    "testFile"
  ],
  [
    "test/jsonschemavalidation.spec.js",
    "test-file/test/JsonSchemaValidation.spec.js.html",
    "test/JsonSchemaValidation.spec.js",
    "testFile"
  ],
  [
    "test/messagefactory.spec.js",
    "test-file/test/MessageFactory.spec.js.html",
    "test/MessageFactory.spec.js",
    "testFile"
  ],
  [
    "test/runtimecapabilities.spec.js",
    "test-file/test/RuntimeCapabilities.spec.js.html",
    "test/RuntimeCapabilities.spec.js",
    "testFile"
  ],
  [
    "test/runtimecatalogue.spec.js",
    "test-file/test/RuntimeCatalogue.spec.js.html",
    "test/RuntimeCatalogue.spec.js",
    "testFile"
  ],
  [
    "test/storagemanager.spec.js",
    "test-file/test/StorageManager.spec.js.html",
    "test/StorageManager.spec.js",
    "testFile"
  ],
  [
    "test/sync.spec.js",
    "test-file/test/Sync.spec.js.html",
    "test/Sync.spec.js",
    "testFile"
  ],
  [
    "test/addressfactorytest.js",
    "test-file/test/addressFactoryTest.js.html",
    "test/addressFactoryTest.js",
    "testFile"
  ],
  [
    "test/utils.spec.js",
    "test-file/test/utils.spec.js.html",
    "test/utils.spec.js",
    "testFile"
  ],
  [
    "utils utils,utils",
    "test-file/test/utils.spec.js.html#lineNumber21",
    "this is test for Utils.",
    "test"
  ],
  [
    "",
    "test-file/test/utils.spec.js.html#lineNumber55",
    "this is test for Utils. should convert a user identity to userURL",
    "test"
  ],
  [
    "",
    "test-file/test/utils.spec.js.html#lineNumber23",
    "this is test for Utils. should divide an url in 3 parts (type, domain, identity)",
    "test"
  ]
]