/**
 * generated by Xtext
 */
package rethink.uml.validation;

import rethink.uml.validation.AbstractClassDiagramValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ClassDiagramValidator extends AbstractClassDiagramValidator {
}
