/*
 * generated by Xtext
 */
package rethink.uml.validation

import org.eclipse.xtext.validation.Check
import rethink.uml.classDiagram.Relation
import rethink.uml.classDiagram.ClassDiagramPackage
import rethink.uml.classDiagram.Clazz

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class ClassDiagramValidator extends AbstractClassDiagramValidator {

	@Check
	def checkInvalidaRelation(Relation rel) {
		if(rel.relType.ext) {
			if (rel.leftRef instanceof Clazz && !(rel.rightRef instanceof Clazz) || rel.rightRef instanceof Clazz && !(rel.leftRef instanceof Clazz))
				error('Invalid extend relation between a class and other element', ClassDiagramPackage.Literals.RELATION__REL_TYPE)
		}
	}
}
